version: '3'
services:
  ubuntu-tdd-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-tdd-container
    volumes:
      - ./../:/workspace/
      - /dev/sda1:/dev/sda1
    command: [ "tail", "-f", "/dev/null" ]
